<a href="https://colab.research.google.com/github/melisabozuklu-lang/Numerical-Methods/blob/main/Laboratory6/question4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# LU decomposition

import numpy as np

def LU_partial_decomposition(matrix):
    n, m = matrix.shape
    P = np.identity(n)
    L = np.identity(n)
    U = matrix.copy()
    PF = np.identity(n)
    LF = np.zeros((n,n))
    for k in range(0, n - 1):
        index = np.argmax(abs(U[k:,k]))
        index = index + k

        # here we do pivoting
        if index != k:
            P = np.identity(n)
            P[[index,k],k:n] = P[[k,index],k:n]
            U[[index,k],k:n] = U[[k,index],k:n]
            PF = np.dot(P,PF)
            LF = np.dot(P,LF)
        # and here decomposition
        L = np.identity(n)
        for j in range(k+1,n):
            L[j,k] = -(U[j,k] / U[k,k])
            LF[j,k] = (U[j,k] / U[k,k])
        U = np.dot(L,U)
    np.fill_diagonal(LF, 1)
    return PF, LF, U

# Usage
A = [[2, 1, 1, 0], [4, 3, 3, 1], [8, 7, 9, 5], [6, 7, 9, 8]]
A = np.array(A)
P1, L1, U1 = LU_partial_decomposition(A)

# Scipy
import scipy
import scipy.linalg
#LU decomposition using linalg.lu library function
P2, L2, U2 = scipy.linalg.lu(A) # P2 = P2.T

print("Input array:")
print(A)
print(" ")
print("Result. Pivoting array:")
print(P1)
print("L and U arrays:")
print(L1,"\n", U1)
print(" ")
print("Result using linalg.lu function. Pivoting array:")
print(P2.T)  # transponed array
print("L and U arrays:")
print(L2,"\n", U2)

Input array:
[[2 1 1 0]
 [4 3 3 1]
 [8 7 9 5]
 [6 7 9 8]]
 
Result. Pivoting array:
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
L and U arrays:
[[ 1.          0.          0.          0.        ]
 [ 0.75        1.          0.          0.        ]
 [ 0.5        -0.28571429  1.          0.        ]
 [ 0.25       -0.42857143  0.33333333  1.        ]] 
 [[ 8.          7.          9.          5.        ]
 [ 0.          1.75        2.25        4.25      ]
 [ 0.          0.         -0.85714286 -0.28571429]
 [ 0.          0.          0.          0.66666667]]
 
Result using linalg.lu function. Pivoting array:
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
L and U arrays:
[[ 1.          0.          0.          0.        ]
 [ 0.75        1.          0.          0.        ]
 [ 0.5        -0.28571429  1.          0.        ]
 [ 0.25       -0.42857143  0.33333333  1.        ]] 
 [[ 8.          7.          9.          5.        ]
 [ 0.          1.75        2.25        4.

In [2]:
import numpy as np
import scipy.linalg

A = np.array([
    [1, 2, 1],
    [1, -2, 2],
    [2, 12, -2]
], dtype=float)

b = np.array([0, 4, 4], dtype=float)

x = scipy.linalg.solve(A, b)

print("Solution:")
print(x)

Solution:
[11.  -2.5 -6. ]


Using LU decomposition and scipy.linalg.solve, the solution of the system was obtained as:

x1 = 11
x2 = -2.5
x3 = -6

The LU decomposition method successfully solved the system of linear equations.

In [3]:
import numpy as np
import scipy.linalg

A = np.array([
    [1, 2, 1],
    [1, -2, 2],
    [2, 12, -2]
], dtype=float)

b = np.array([0, 4, 4], dtype=float)

# LU decomposition
P, L, U = scipy.linalg.lu(A)

print("L matrix:")
print(L)

print("\nU matrix:")
print(U)

# Solve Ly = b
y = scipy.linalg.solve(L, b)

print("\ny vector:")
print(y)

# Solve Ux = y
x = scipy.linalg.solve(U, y)

print("\nSolution vector x:")
print(x)

L matrix:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 0.5 1. ]]

U matrix:
[[ 2.  12.  -2. ]
 [ 0.  -8.   3. ]
 [ 0.   0.   0.5]]

y vector:
[0. 4. 2.]

Solution vector x:
[-2.  1.  4.]
